version: "3.1"
services:
  mysql-dev:
    platform: linux/x86_64
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Computador1
      MYSQL_DATABASE: Hackatonapp
    ports:
      - 3307:3306
    volumes:
      - mysql-dev:/tmp

volumes:
  mysql-dev:
    external: false
